version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: empresa
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - appnet
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
      PMA_ABSOLUTE_URI: http://localhost:8081/
    networks:
      - appnet
    depends_on:
      - mysql

  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: usuario
      WORDPRESS_DB_PASSWORD: usuario123
      WORDPRESS_DB_NAME: empresa
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - appnet
    depends_on:
      - mysql

  backend:
    build: ./backend
    environment:
      DB_HOST: mysql
      DB_USER: usuario
      DB_PASSWORD: usuario123
      DB_NAME: empresa
    networks:
      - appnet
    depends_on:
      - mysql

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    networks:
      - appnet
  frontend:
    build: ./frontend
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - appnet
    depends_on:
      - wordpress
      - backend
      - frontend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - appnet

  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - "8082:1234"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    networks:
      - appnet
    depends_on:
      - mongodb

networks:
  appnet:
    driver: bridge

volumes:
  mysql_data:
  mongodb_data:
  wordpress_data:
